name: Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Instalar cloudflared
        run: |
          curl -L --output cloudflared.deb \
            https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb

          sudo dpkg -i cloudflared.deb

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Configurar SSH
        run: |
          cat <<EOF > ~/.ssh/config
          Host ssh.bokargiu.com.br
              User bokargiu
              IdentityFile ~/.ssh/id_ed25519
              ProxyCommand cloudflared access ssh --hostname %h
          EOF

          chmod 600 ~/.ssh/config

      - name: Testar conexão
        run: |
          ssh -o StrictHostKeyChecking=no ssh.bokargiu.com.br \
            "echo 'SSH pelo Cloudflare Tunnel funcionando!'"
